# Generated by Django 2.2.24 on 2021-12-16 12:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contactme', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contact',
        ),
    ]
