# Generated by Django 2.2.24 on 2021-12-16 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_auto_20211216_1620'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Post',
        ),
    ]
