# Generated by Django 2.2.24 on 2021-12-17 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hush', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='instagram',
            field=models.TextField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='cover',
            field=models.ImageField(upload_to='media/images/'),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.TextField(),
        ),
    ]
