# Generated by Django 2.2.24 on 2021-12-17 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hush', '0002_auto_20211217_1816'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='tiktok',
            field=models.TextField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='instagram',
            field=models.TextField(max_length=100, null=True),
        ),
    ]
