# Generated by Django 2.2.24 on 2021-12-22 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hush', '0003_auto_20211217_1824'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='cover',
        ),
        migrations.AddField(
            model_name='post',
            name='image_1',
            field=models.ImageField(blank=True, upload_to='media/images/'),
        ),
        migrations.AddField(
            model_name='post',
            name='image_2',
            field=models.ImageField(blank=True, upload_to='media/images/'),
        ),
        migrations.AddField(
            model_name='post',
            name='image_3',
            field=models.ImageField(blank=True, upload_to='media/images/'),
        ),
        migrations.AddField(
            model_name='post',
            name='image_4',
            field=models.ImageField(blank=True, upload_to='media/images/'),
        ),
    ]
