# Generated by Django 2.2.24 on 2021-12-22 23:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hush', '0004_auto_20211223_0218'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='image_1',
            new_name='image1',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='image_2',
            new_name='image2',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='image_3',
            new_name='image3',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='image_4',
            new_name='image4',
        ),
    ]
