# Generated by Django 2.2.24 on 2021-12-23 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hush', '0008_auto_20211223_0250'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image1',
            field=models.ImageField(blank=True, upload_to='media/images/'),
        ),
        migrations.DeleteModel(
            name='Gallery',
        ),
    ]
