# Generated by Django 2.2.24 on 2021-12-23 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hush', '0009_auto_20211224_0234'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image2',
            field=models.ImageField(blank=True, upload_to='media/images/'),
        ),
        migrations.AddField(
            model_name='post',
            name='image3',
            field=models.ImageField(blank=True, upload_to='media/images/'),
        ),
        migrations.AddField(
            model_name='post',
            name='image4',
            field=models.ImageField(blank=True, upload_to='media/images/'),
        ),
    ]
